cmd: "make all && make CreateTestSuiteExecutable"
name: Build
cwd: "{PROJECT_PATH}/build"
errorMatch: "\\s*(?<file>[\\/0-9a-zA-Z\\._]+):(?<line>\\d+):?(?<col>\\d+)?\\s+(?<message>.+)"
targets:
    Configure:
        cmd: "mkdir -p {PROJECT_PATH}/build && cd {PROJECT_PATH}/build && cmake -DCMAKE_BUILD_TYPE=Release ../"

    BuilAndRun:
        cmd: "make all && make CreateTestSuiteExecutable && {PROJECT_PATH}/bin/Release/test/run_all_tests.py"
        cwd: "{PROJECT_PATH}/build"
        atomCommandName: BuildAndRun

    BuilAndRunVerbose:
        cmd: "make all && make CreateTestSuiteExecutable && {PROJECT_PATH}/bin/Release/test/run_all_tests.py -v"
        atomCommandName: BuilAndRunVerbose
        cwd: "{PROJECT_PATH}/build"
