cmd: "make -j 4 all && make CreateTestSuiteExecutable"
name: Build
cwd: "{PROJECT_PATH}/build"
errorMatch: "\\s*(?<file>[\\/0-9a-zA-Z\\._]+):(?<line>\\d+):?(?<col>\\d+)?:?\\s?error:\\s+(?<message>.+)"
warningMatch: "\\s*(?<file>[\\/0-9a-zA-Z\\._]+):(?<line>\\d+):?(?<col>\\d+)?:?\\s?warning:\\s+(?<message>.+)"
targets:
    Configure:
        cmd: "mkdir -p {PROJECT_PATH}/build && cd {PROJECT_PATH}/build && cmake -DCMAKE_BUILD_TYPE=Release ../"

    BuilAndRun:
        atomCommandName: BuildAndRun

        cmd: "make -j 4 all && make CreateTestSuiteExecutable && {PROJECT_PATH}/bin/Release/test/run_all_tests.py"
        cwd: "{PROJECT_PATH}/build"

        errorMatch:
            - "\\s*(?<file>[\\/0-9a-zA-Z\\._]+):(?<line>\\d+):?(?<col>\\d+)?:?\\s?error:\\s+(?<message>.+)"
            - "\\s*(?<file>[\\/0-9a-zA-Z\\._]+):(?<line>\\d+):?(?<col>\\d+)?\\s+(?<message>.+)"
        warningMatch: "\\s*(?<file>[\\/0-9a-zA-Z\\._]+):(?<line>\\d+):?(?<col>\\d+)?:?\\s?warning:\\s+(?<message>.+)"

    BuilAndRunVerbose:
        atomCommandName: BuilAndRunVerbose

        cmd: "make -j 4 all && make CreateTestSuiteExecutable && {PROJECT_PATH}/bin/Release/test/run_all_tests.py -v"
        cwd: "{PROJECT_PATH}/build"

        errorMatch:
            - "\\s*(?<file>[\\/0-9a-zA-Z\\._]+):(?<line>\\d+):?(?<col>\\d+)?:?\\s?error:\\s+(?<message>.+)"
            - "\\s*(?<file>[\\/0-9a-zA-Z\\._]+):(?<line>\\d+):?(?<col>\\d+)?\\s+(?<message>.+)"
        warningMatch: "\\s*(?<file>[\\/0-9a-zA-Z\\._]+):(?<line>\\d+):?(?<col>\\d+)?:?\\s?warning:\\s+(?<message>.+)"

    Clean:
        atomCommandName: Clean

        cmd: "make clean"
        cwd: "{PROJECT_PATH}/build"
