.build_template:
    script: &build_commands
        - $CI_PROJECT_DIR/build.sh
        - $CI_PROJECT_DIR/bin/Release/test/run_all_tests.py

image: alexiynew/docker_image

stages:
    - build

# Clang
# ============================
build:clang:
    stage: build

    before_script:
        - export CXX=clang++
        - export CC=clang

    script: *build_commands

# Gcc
# ============================
build:gcc:
    stage: build

    before_script:
        - export CXX=g++
        - export CC=gcc

    # diasble it for now
    # script: *build_commands
    script:
        - echo "Gcc compilation is disabled."
