.build_template: &build_commands
    script:
        - mkdir build && cd ./build
        - cmake ../
        - make

build_with_clang:
    image: alexiynew/docker_image

    before_script:
        - export CXX=clang++
        - export CC=clang

    <<: &build_commands

build_with_gcc:
    script: 
        - echo "Run gcc job."