.build_template: 
    script: &build_commands
        - mkdir build && cd ./build
        - cmake ../
        - nice make


image: alexiynew/docker_image


build_with_clang:
    before_script:
        - export CXX=clang++
        - export CC=clang
        
    script: *build_commands


build_with_gcc:
    before_script:
        - export CXX=g++
        - export CC=gcc

    script: *build_commands