.build_template: 
    script: &build_commands
        - mkdir build && cd ./build
        - cmake ../
        - make

build_with_clang:
    image: alexiynew/docker_image

    before_script:
        - export CXX=clang++
        - export CC=clang
        
    script: *build_commands
        

build_with_gcc:
    script: 
        - echo "Run gcc job."