.build_template: 
    script: &build_commands
        - ./build.sh
        
.test_template:
    script: &test_commands
        - ./bin/Release/test/run_all_tests.py 

image: alexiynew/docker_image

stages:
    - build
    - test

build_with_clang:
    stage: build

    before_script:
        - export CXX=clang++
        - export CC=clang
        
    script: *build_commands


build_with_gcc:
    stage: build

    before_script:
        - export CXX=g++
        - export CC=gcc

    script: *build_commands
