job_clang:
    image: alexiynew/docker_image

    script: 
        - echo "Run clang job."
        - clang++ --verion
        - echo ${CXX} 
        - echo ${CC}

job_gcc:
    script: 
        - echo "Run gcc job."