job_clang:
    image: alexiynew/docker_image

    before_script:
        export CXX=clang++
        export CC=clang

    script: 
        - echo "Run clang job."
        - clang++ --version
        - echo ${CXX} 
        - echo ${CC}

job_gcc:
    script: 
        - echo "Run gcc job."