env:
  global:
    - CODECOV_TOKEN=67a4f583-c9f2-4c56-9dc4-bf421bb11a63
    - WORKDIR="/home/framework"

matrix:
  include:
    - os: linux
      env:
        - CC=clang
        - CXX=clang++
        - COMMAND="meson build && cd build && ninja"
      sudo: required
      services:
        - docker

    - os: linux
      env:
        - CC=gcc
        - CXX=g++
        - COMMAND="meson build && cd build && ninja"
      sudo: required
      services:
        - docker

    - os: linux
      env:
        - CC=gcc
        - CXX=g++
        - COMMAND="meson -D b_coverage=true build && cd build && ninja test"
      sudo: required
      services:
        - docker
        
      after_success:
        - bash <(curl -s https://codecov.io/bash)

language: generic

branches:
  only:
    - master
    - dev

install:
  - docker pull alexiynew/docker_image

script:
  - docker run -it -e COMMAND="${COMMAND}" -e CC="${CC}" -e CXX="${CXX}" -w "${WORKDIR}" -v "${TRAVIS_BUILD_DIR}:${WORKDIR}" alexiynew/docker_image 
