sudo: required

language: generic

services:
  - docker
  
before_install:
  - pwd
  - docker pull alexiynew/docker_image
  - docker run --name roller -it -d -v $(pwd):/home/alexiynew/game_framework alexiynew/docker_image bash -c "./build.sh -c clang"
  - docker rm roller

