sudo: required
dist: trusty

language: generic

addons:
    apt:
        packages:
            - cmake

matrix:
    include:
    - compiler: gcc
      addons:
        apt:
            sources:
                - ubuntu-toolchain-r-test
            packages:
                - g++-4.9
      env: CXX=g++-4.9

    - compiler: clang
      addons:
        apt:
            sources:
                - ubuntu-toolchain-r-test
                - llvm-toolchain-precise-3.8
            packages:
                - clang-3.8
      env: CXX=clang++-3.8

script:
    - mkdir build && cd ./build
    - cmake ../
    - make

