matrix:
  include:
    - os: linux
      dist: trusty
      env: 
        - COMPILLER=clang
        - TASK="clean,build,test"
      sudo: required

    - os: linux
      dist: trusty
      env: 
        - COMPILLER=clang
        - TASK="clean,build,test"
      sudo: required

    - os: linux      
      dist: trusty
      env: 
        - COMPILLER=gcc
        - TASK="clean,coverage"
      sudo: required

language: generic

branches:
  only:
    - master
    - dev

services:
  - docker

before_install:
  - pwd
  - docker pull alexiynew/docker_image

install: true

script:
  - docker run -it -v "$(pwd):/home/framework" alexiynew/docker_image bash -c "export COMPILLER=$COMPILLER TASK=$TASK && /home/framework/travis_run.sh"
