language: cpp

before_install:
    - sudo add-apt-repository "ppa:ubuntu-toolchain-r/test" -y
    - echo "deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.8 main" | sudo tee -a /etc/apt/sources.list
    - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 15CF4D18AF4F7421
    - sudo apt-get update -q

install:
    - sudo apt-get install clang-3.8 -y
    - sudo apt-get install gcc-4.8 -y
    - sudo apt-get install cmake -y

script:
    - pwd
    - mkdir build
    - cd ./build
    - cmake ../
    - make

compiler:
    - gcc
    - clang
