language: cpp

addons:
    apt:
        sources:
            - sourceline: 'http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.8 main'
            - sourceline: 'ppa:ubuntu-toolchain-r/test'

install:
    - sudo -E apt-get install clang-3.8 -y

compiler:
    - gcc
    - clang
