matrix:
  include:
    - os: linux
      dist: trusty
      compiler: clang
      sudo: required
      
    - os: linux
      dist: trusty
      compiler: gcc
      sudo: required
  
language: generic

branches:
  only:
  - master

services:
  - docker

before_install:
  - pwd
  - docker pull alexiynew/docker_image

install: true

script:
  - docker run -it -v "$(pwd):/home/framework" alexiynew/docker_image bash -c "ls -al /home/framework"
  - docker run -it -v "$(pwd):/home/framework" alexiynew/docker_image bash -c "/home/framework/build.sh -c clang"
  - docker run -it -v "$(pwd):/home/framework" alexiynew/docker_image bash -c "/home/framework/bin/Release/test/run_all_tests.py"
