sudo: required

language: generic

services:
  - docker
  
before_install:
  - pwd
  - docker pull alexiynew/docker_image
  - docker run --name roller -it -d
  - pwd
  - exit
  - docker rm roller

script:
  - build.sh -c clang
