env:
  global:
    - CODECOV_TOKEN=67a4f583-c9f2-4c56-9dc4-bf421bb11a63

matrix:
  include:
    - os: linux
      env:
        - COMPILLER=clang
        - TASK="clean build test"
      sudo: required
      services:
        - docker

    - os: linux
      env:
        - COMPILLER=gcc
        - TASK="clean build test"
      sudo: required
      services:
        - docker

    - os: osx
      osx_image: xcode8.3
      env:
        - TASK="clean build test"

    - os: osx
      osx_image: xcode9.1
      env:
        - TASK="clean build test"

    - os: linux
      dist: trusty
      env:
        - COMPILLER=gcc
        - TASK="clean coverage"
      sudo: required
      services:
        - docker

language: generic

branches:
  only:
    - master
    - dev

install:
  - ./travis_install.sh

script:
  - ./travis_run.sh
