env:
  global:
    - CODECOV_TOKEN=67a4f583-c9f2-4c56-9dc4-bf421bb11a63

matrix:
  include:
    - os: linux
      env:
        - CC_COMPILER=clang
        - CXX_COMPILER=clang++
        - TASK="test"
      sudo: required
      services:
        - docker

    - os: linux
      env:
        - CC_COMPILER=gcc
        - CXX_COMPILER=g++
        - TASK="test"
      sudo: required
      services:
        - docker

    - os: linux
      env:
        - CC_COMPILER=gcc
        - CXX_COMPILER=g++
        - TASK="clean coverage"
      sudo: required
      services:
        - docker

language: generic

branches:
  only:
    - master
    - dev

install:
  - ./misc/travis_install.sh

script:
  - ./misc/travis_run.sh
