language: cpp

addons:
    apt:
        sources:
            - sourceline: 'http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.8 main'
            - sourceline: 'ppa:ubuntu-toolchain-r/test'

before_install:
    - sudo add-apt-repository "ppa:ubuntu-toolchain-r/test" -y
    - echo "deb http://repo.varnish-cache.org/ubuntu/ precise varnish-3.0" | sudo tee -a /etc/apt/sources.list
    - sudo apt-get update -q

install:
    - sudo apt-get install clang-3.8 -y

compiler:
    - gcc
    - clang
