matrix:
  include:
    - os: linux
      dist: trusty
      env: COMPILLER=clang
      sudo: required

    - os: linux
      dist: trusty
      env: COMPILLER=gcc
      sudo: required

language: generic

branches:
  only:
  - master
  - dev

services:
  - docker

before_install:
  - pwd
  - docker pull alexiynew/docker_image

install: true

script:
  - docker run -it -v "$(pwd):/home/framework" alexiynew/docker_image bash
  - pwd
  - ls -al /home/framework
  # - docker run -it -v "$(pwd):/home/framework" alexiynew/docker_image bash -c "/home/framework/build.sh -c $COMPILLER -t build"
  # - docker run -it -e DISPLAY=$DISPLAY:99 -v "$(pwd):/home/framework" alexiynew/docker_image bash -c "/home/framework/build.sh -t test"
  # Xvfb :1 -screen 0 1024x768x16 &> xvfb.log &
  #  ps aux | grep X