language: cpp

addons:
    apt:
        sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'http://archive.ubuntu.com/ubuntu/ precise main restricted'

        packages:
            - cmake
            - g++
            - clang-3.8

compiler:
    - gcc
    - clang

install: true
