sudo: required

language: generic

services:
  - docker
  
before_install:
  - pwd
  - docker pull alexiynew/docker_image
  - docker run --name roller -it -d alexiynew/docker_image
  - pwd

script:
  - build.sh -c clang
