sudo: required
dist: trusty

language: generic

matrix:
    include:
    - compiler: gcc
      addons:
        apt:
            sources:
                - ubuntu-toolchain-r-test
            packages:
                - g++-4.9
                - cmake
      env:
        - CXX=g++-4.9
        - CC=gcc-4.9

    - compiler: clang
      addons:
        apt:
            sources:
                - ubuntu-toolchain-r-test
                - llvm-toolchain-precise-3.8
            packages:
                - clang-3.8
                - cmake
      env:
        - CXX=clang++-3.8
        - CC=clang-3.8

script:
    - mkdir build && cd ./build
    - cmake ../
    - make

