matrix:
  include:
    - os: linux
      dist: trusty
      env: COMPILLER=clang
      sudo: required

    - os: linux
      dist: trusty
      env: COMPILLER=gcc
      sudo: required

language: generic

branches:
  only:
  - master

services:
  - docker

before_install:
  - pwd
  - docker pull alexiynew/docker_image

install: true

before_script:
  - export DISPLAY=:99.0
  - bash -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

script:
  - docker run -it -v "$(pwd):/home/framework" alexiynew/docker_image bash -c "ls -al /home/framework"
  - docker run -it -v "$(pwd):/home/framework" alexiynew/docker_image bash -c "/home/framework/build.sh -c $COMPILLER -t build"
  - docker run -it -e DISPLAY=$DISPLAY:99 -v "$(pwd):/home/framework" alexiynew/docker_image bash -c "/home/framework/build.sh -t test"
